import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import { walkProject } from './walker.js';
import { parseFile } from './treesitter.js';
import type { FileSymbols } from './treesitter.js';
import { buildGraph, buildReverseIndex } from '../graph/index.js';
import type { GraphNode, GraphEdge } from '../graph/index.js';
import { saveIndex, saveGraph, saveReverseIndex, saveMeta, saveContext, loadSummaries, loadConfig } from '../storage/index.js';
import { refreshAgentFiles } from '../agents.js';
import { serializeIndex } from '../mcp/serializer.js';

function buildContextMd(body: string): string {
  return [
    '<!-- Auto-generated by larkx on every `larkx index` run. Do not edit manually. -->',
    '',
    '# Codebase Index',
    '',
    'Compact map of all files, functions, classes, and imports in this project.',
    'Read this before exploring source files. For MCP clients, use larkx MCP tools instead.',
    '',
    '---',
    '',
    body,
  ].join('\n');
}

function sha256(content: string): string {
  return crypto.createHash('sha256').update(content, 'utf-8').digest('hex');
}

function renderProgressBar(current: number, total: number, width = 20): string {
  const pct = total === 0 ? 100 : Math.floor((current / total) * 100);
  const filled = Math.floor((current / (total || 1)) * width);
  const bar = '='.repeat(filled) + '>'.padEnd(width - filled, ' ');
  return `[${bar}] ${pct}%`;
}

export async function indexProject(
  projectRoot: string,
  options: { force?: boolean } = {}
): Promise<{ nodes: GraphNode[]; edges: GraphEdge[]; meta: object }> {
  const config = loadConfig(projectRoot);
  const files = walkProject(projectRoot, config.exclude);

  // load existing meta to get stored hashes
  const metaPath = path.join(projectRoot, '.larkx', 'meta.json');
  let storedHashes: Record<string, string> = {};
  let cachedSymbols: Record<string, FileSymbols> = {};

  if (!options.force && fs.existsSync(metaPath)) {
    try {
      const meta = JSON.parse(fs.readFileSync(metaPath, 'utf-8'));
      storedHashes = meta.fileHashes ?? {};
    } catch {
      storedHashes = {};
    }
  }

  // load cached index for reuse
  const indexPath = path.join(projectRoot, '.larkx', 'index.json');
  if (!options.force && fs.existsSync(indexPath)) {
    try {
      const idx = JSON.parse(fs.readFileSync(indexPath, 'utf-8'));
      if (Array.isArray(idx)) {
        for (const sym of idx) {
          if (sym && sym.file) cachedSymbols[sym.file] = sym;
        }
      }
    } catch {
      cachedSymbols = {};
    }
  }

  const allSymbols: FileSymbols[] = [];
  const newHashes: Record<string, string> = { ...storedHashes };
  let changed = 0;
  let cached = 0;

  process.stdout.write(`Indexing... ${renderProgressBar(0, files.length)}\r`);

  for (let i = 0; i < files.length; i++) {
    const relPath = files[i];
    const fullPath = path.join(projectRoot, relPath);

    let content: string;
    try {
      content = fs.readFileSync(fullPath, 'utf-8');
    } catch {
      continue;
    }

    const hash = sha256(content);
    const storedHash = storedHashes[relPath];

    if (!options.force && storedHash === hash && cachedSymbols[relPath]) {
      allSymbols.push(cachedSymbols[relPath]);
      cached++;
    } else {
      const sym = await parseFile(relPath, content);
      allSymbols.push(sym);
      newHashes[relPath] = hash;
      changed++;
    }

    if (i % 5 === 0 || i === files.length - 1) {
      process.stdout.write(`Indexing... ${renderProgressBar(i + 1, files.length)}\r`);
    }
  }

  process.stdout.write('\n');

  const graph = buildGraph(allSymbols);

  const langCounts: Record<string, number> = {};
  let functionCount = 0;
  let classCount = 0;

  for (const sym of allSymbols) {
    langCounts[sym.lang] = (langCounts[sym.lang] ?? 0) + 1;
    functionCount += sym.functions.length;
    classCount += sym.classes.length;
  }

  const meta = {
    lastIndexed: new Date().toISOString(),
    fileCount: files.length,
    functionCount,
    classCount,
    edgeCount: graph.edges.length,
    languages: langCounts,
    fileHashes: newHashes,
  };

  saveIndex(projectRoot, allSymbols);
  saveGraph(projectRoot, graph);
  saveReverseIndex(projectRoot, buildReverseIndex(graph));
  saveMeta(projectRoot, meta);

  const summaries = (loadSummaries(projectRoot) as Record<string, string> | null) ?? {};
  const contextBody = serializeIndex(graph.nodes, summaries, { level: 2, fileSymbols: allSymbols });
  saveContext(projectRoot, buildContextMd(contextBody));

  if (config.agents?.length) {
    refreshAgentFiles(projectRoot, config.agents, config.mcpEnabled ?? false);
  }

  console.log(
    `✓ Indexed ${files.length} files (${changed} changed, ${cached} cached), ${functionCount} functions, ${classCount} classes`
  );

  return { nodes: graph.nodes, edges: graph.edges, meta };
}

export async function watchProject(projectRoot: string): Promise<void> {
  const { default: chokidar } = await import('chokidar');
  const { loadIndex, saveIndex, loadGraph, saveGraph } = await import('../storage/index.js');

  const supported = /\.(ts|tsx|js|jsx|mjs|cjs|py|go|rs|java|cpp|c|cs)$/;

  console.log('Watching for changes... (Ctrl+C to stop)');

  const watcher = chokidar.watch(projectRoot, {
    ignored: [
      /node_modules/,
      /\.git/,
      /dist/,
      /build/,
      /\.larkx/,
      /\.next/,
    ],
    persistent: true,
    ignoreInitial: true,
  });

  async function reindexFile(fullPath: string): Promise<void> {
    const relPath = path.relative(projectRoot, fullPath).replace(/\\/g, '/');
    if (!supported.test(relPath)) return;

    let content: string;
    try {
      content = fs.readFileSync(fullPath, 'utf-8');
    } catch {
      return;
    }

    const sym = await parseFile(relPath, content);

    const currentIndex = (loadIndex(projectRoot) as FileSymbols[] | null) ?? [];
    const idx = currentIndex.filter((s: FileSymbols) => s.file !== relPath);
    idx.push(sym);
    saveIndex(projectRoot, idx);

    const graph = buildGraph(idx);
    saveGraph(projectRoot, graph);
    saveReverseIndex(projectRoot, buildReverseIndex(graph));

    const summaries = (loadSummaries(projectRoot) as Record<string, string> | null) ?? {};
    saveContext(projectRoot, buildContextMd(serializeIndex(graph.nodes, summaries, { level: 2, fileSymbols: idx })));

    console.log(`↻ Re-indexed ${relPath}`);
  }

  function removeFile(fullPath: string): void {
    const relPath = path.relative(projectRoot, fullPath).replace(/\\/g, '/');
    if (!supported.test(relPath)) return;

    const currentIndex = (loadIndex(projectRoot) as FileSymbols[] | null) ?? [];
    const idx = currentIndex.filter((s: FileSymbols) => s.file !== relPath);
    saveIndex(projectRoot, idx);

    const graph = buildGraph(idx);
    saveGraph(projectRoot, graph);
    saveReverseIndex(projectRoot, buildReverseIndex(graph));

    const summaries = (loadSummaries(projectRoot) as Record<string, string> | null) ?? {};
    saveContext(projectRoot, buildContextMd(serializeIndex(graph.nodes, summaries, { level: 2, fileSymbols: idx })));

    console.log(`✕ Removed ${relPath} from index`);
  }

  watcher.on('add', reindexFile);
  watcher.on('change', reindexFile);
  watcher.on('unlink', removeFile);
}
